---
# Source: darkube-stateless/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
    name: toos
    labels:
        app.kubernetes.io/name: toos-darkube-stateless
        helm.sh/chart: darkube-stateless-1.0.1
        app.kubernetes.io/instance: toos
        app.kubernetes.io/managed-by: Helm
        darkube.hamravesh.com/app-id: 670d0a41-1374-46a5-bb06-41d4fe78e360
        darkube.hamravesh.com/release-id: 863a4c8a-58ff-4dba-a3ab-b582d40e0845
spec:
    type: ClusterIP
    ports:
    - name: main
      port: 8000
      targetPort: 8000
      protocol: TCP


    selector:
        app.kubernetes.io/name: toos-darkube-stateless
        app.kubernetes.io/instance: toos
---
# Source: darkube-stateless/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toos
  labels:
    app.kubernetes.io/name: toos-darkube-stateless
    helm.sh/chart: darkube-stateless-1.0.1
    app.kubernetes.io/instance: toos
    app.kubernetes.io/managed-by: Helm
    darkube.hamravesh.com/app-id: 670d0a41-1374-46a5-bb06-41d4fe78e360
    darkube.hamravesh.com/release-id: 863a4c8a-58ff-4dba-a3ab-b582d40e0845
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: toos-darkube-stateless
      app.kubernetes.io/instance: toos
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        rollme: "hyboXW"
      labels:
        app.kubernetes.io/name: toos-darkube-stateless
        app.kubernetes.io/instance: toos
        darkube.hamravesh.com/app-id: 670d0a41-1374-46a5-bb06-41d4fe78e360
        darkube.hamravesh.com/release-id: 863a4c8a-58ff-4dba-a3ab-b582d40e0845
    spec:
      serviceAccountName:  default
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  -  toos
              topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: false
      enableServiceLinks: false
      
      containers:
      - name:  main
        image: registry.hamdocker.ir/farlineedu/toos:4250c82a
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: main
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            ephemeral-storage: 500M
            memory: 500M
          limits:
            cpu: 250m
            ephemeral-storage: 500M
            memory: 500M
      nodeSelector:
        darkube.hamravesh.com/deploy: "true"
      tolerations:
        - effect: NoSchedule
          key: darkube
          operator: Exists
---
# Source: darkube-stateless/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: toos-custom-subdomain
    labels:
        app.kubernetes.io/name: toos-darkube-stateless
        helm.sh/chart: darkube-stateless-1.0.1
        app.kubernetes.io/instance: toos
        app.kubernetes.io/managed-by: Helm
        darkube.hamravesh.com/app-id: 670d0a41-1374-46a5-bb06-41d4fe78e360
        darkube.hamravesh.com/release-id: 863a4c8a-58ff-4dba-a3ab-b582d40e0845
    annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        traefik.ingress.kubernetes.io/redirect-permanent: "true"
        ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
    - host: "farline.darkube.app"
      http:
        paths:
          - path: "/"
            backend:
              service:
                name: "toos"
                port:
                  name: "main"
            pathType: "Prefix"
---
# Source: darkube-stateless/templates/secrets.yaml
---
