# Generated by Django 3.2.9 on 2022-01-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_resume_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='resume',
        ),
        migrations.AddField(
            model_name='teacher',
            name='reshte',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
