# Generated by Django 4.0.1 on 2022-01-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_text_teacher_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='lesson',
            new_name='text',
        ),
    ]
