# Generated by Django 3.2.9 on 2022-01-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_giude_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
        migrations.AddField(
            model_name='course',
            name='kind',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
