# Generated by Django 3.2.9 on 2022-01-30 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20220130_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='kind_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.kind'),
        ),
        migrations.AlterField(
            model_name='course',
            name='kind',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
