# Generated by Django 3.2.9 on 2022-01-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20220130_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='kind',
        ),
    ]
