# Generated by Django 3.2.9 on 2022-01-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_course_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
