# Generated by Django 3.2.9 on 2022-01-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_kind_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
