# Generated by Django 3.2.9 on 2022-01-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_kind_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
        ),
    ]
