# Generated by Django 3.2.9 on 2022-01-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_soal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soal',
            old_name='matn',
            new_name='question',
        ),
    ]
