# Generated by Django 3.2.9 on 2022-01-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_rename_matn_soal_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='question',
            field=models.TextField(),
        ),
    ]
