# Generated by Django 3.2.8 on 2022-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
