# Generated by Django 3.2.8 on 2022-02-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_cover_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='picture',
            field=models.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(upload_to='teachers'),
        ),
    ]
