# Generated by Django 3.2.8 on 2022-02-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_session_coruse'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
