# Generated by Django 3.2.8 on 2022-02-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_grade_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='soal',
            new_name='Question',
        ),
        migrations.RemoveField(
            model_name='course',
            name='link',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video_preview',
        ),
    ]
