# Generated by Django 3.2.8 on 2022-03-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20220225_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='id_course',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
