# Generated by Django 3.2.8 on 2022-03-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_course_id_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
