# Generated by Django 3.2.8 on 2022-03-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_auto_20220304_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id_course',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='reshte',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
