# Generated by Django 3.2.8 on 2022-03-04 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_auto_20220304_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='reshte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='course.kind'),
        ),
    ]
