# Generated by Django 3.2.8 on 2022-03-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_alter_teacher_reshte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='code',
        ),
        migrations.RemoveField(
            model_name='kind',
            name='code',
        ),
    ]
