# Generated by Django 3.2.8 on 2022-03-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_auto_20220304_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
