# Generated by Django 3.2.8 on 2022-03-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_course_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_preview',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
