# Generated by Django 3.2.8 on 2022-03-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_auto_20220304_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='course', to='course.Session_coruse'),
        ),
    ]
