# Generated by Django 3.2.8 on 2022-03-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_alter_course_sessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='kind_course',
            new_name='kind',
        ),
        migrations.AddField(
            model_name='news',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='course.grade'),
        ),
        migrations.AddField(
            model_name='news',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='course.kind'),
        ),
        migrations.CreateModel(
            name='Plan_weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='course.grade')),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='course.kind')),
            ],
        ),
    ]
