# Generated by Django 3.2.8 on 2022-03-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0038_auto_20220304_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='reshte',
            new_name='kind',
        ),
        migrations.AddField(
            model_name='course',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
