# Generated by Django 3.2.8 on 2022-03-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0039_auto_20220304_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sessions',
        ),
    ]
