# Generated by Django 3.2.8 on 2022-03-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0041_course_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
