# Generated by Django 3.2.8 on 2022-03-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0042_grade_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='code',
        ),
    ]
