# Generated by Django 3.2.8 on 2022-03-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0044_kind_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to='package/')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='picture',
            field=models.ImageField(default=1, upload_to='grade/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kind',
            name='picture',
            field=models.ImageField(upload_to='kind/'),
        ),
        migrations.AddField(
            model_name='kind',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kind', to='course.package'),
        ),
    ]
