# Generated by Django 3.2.8 on 2022-03-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0046_auto_20220307_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
