# Generated by Django 3.2.8 on 2022-03-16 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0049_auto_20220307_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
