# Generated by Django 3.2.8 on 2022-03-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0050_course_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='link',
            new_name='Text',
        ),
    ]
