# Generated by Django 3.2.8 on 2022-03-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0051_rename_link_course_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan_weeks',
        ),
    ]
