# Generated by Django 3.2.8 on 2022-03-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0056_alter_course_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
