# Generated by Django 3.2.8 on 2022-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0058_auto_20220330_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_coruse',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
