# Generated by Django 3.2.8 on 2022-05-30 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0059_alter_session_coruse_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.AddField(
            model_name='course',
            name='time_1',
            field=models.CharField(default=121212, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onlineClass', to='course.course'),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='day',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='month',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='next_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='year',
            field=models.IntegerField(default=1400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session_coruse',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='session_coruse',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session_coruse',
            name='time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='session_coruse',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
