# Generated by Django 3.2.8 on 2022-04-01 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0059_alter_session_coruse_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
