# Generated by Django 3.2.8 on 2022-04-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0060_alter_course_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
    ]
