# Generated by Django 3.2.8 on 2022-04-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0061_remove_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_1',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
