# Generated by Django 3.2.8 on 2022-04-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0062_course_time_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_coruse',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session_coruse',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
