# Generated by Django 3.2.8 on 2022-04-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0063_auto_20220401_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
