# Generated by Django 3.2.8 on 2022-04-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0064_alter_course_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onlineClass', to='course.course'),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='next_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
