# Generated by Django 3.2.8 on 2022-05-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0065_auto_20220430_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_coruse',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
