# Generated by Django 3.2.8 on 2022-02-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
