# Generated by Django 3.2.8 on 2022-02-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_alter_cart_total_peyment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='stuff.coupon'),
            preserve_default=False,
        ),
    ]
