# Generated by Django 3.2.8 on 2022-02-25 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0006_auto_20220225_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.coupon'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_peyment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
