# Generated by Django 3.2.8 on 2022-04-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0009_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='pay',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='code',
            field=models.DecimalField(decimal_places=3, max_digits=5, unique=True),
        ),
    ]
