# Generated by Django 3.2.8 on 2022-05-15 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0066_session_coruse_is_free'),
        ('stuff', '0012_alter_receipt_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='course',
        ),
        migrations.AddField(
            model_name='receipt',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='receipt', to='course.Course'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='stuff.department'),
        ),
    ]
