# Generated by Django 3.2.8 on 2022-05-28 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0014_receipt_hash_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 17, 50, 38, 250693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 17, 50, 38, 255699, tzinfo=utc)),
        ),
    ]
