# Generated by Django 3.2.8 on 2022-05-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0015_auto_20220528_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
