# Generated by Django 3.2.8 on 2022-05-28 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0016_auto_20220528_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
