# Generated by Django 3.2.8 on 2022-03-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0007_auto_20220225_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuff',
            old_name='id_course',
            new_name='code',
        ),
    ]
