# Generated by Django 3.2.8 on 2022-04-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0010_auto_20220430_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='code',
            field=models.DecimalField(decimal_places=5, max_digits=5, unique=True),
        ),
    ]
