# Generated by Django 3.2.8 on 2021-11-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211026_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='national_code',
            new_name='nationalCode',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phoneNumber',
        ),
    ]
