# Generated by Django 3.2.8 on 2022-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0053_auto_20220316_2047'),
        ('accounts', '0003_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='course.Course'),
        ),
    ]
