# Generated by Django 3.2.8 on 2021-11-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211102_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationalCode',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
