# Generated by Django 3.2.8 on 2022-03-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0053_auto_20220316_2047'),
        ('accounts', '0004_user_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course.Course'),
        ),
    ]
