# Generated by Django 3.2.8 on 2021-11-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211102_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='frist_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
