# Generated by Django 3.2.8 on 2021-11-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211103_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
