# Generated by Django 3.2.8 on 2021-11-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('accounts', '0007_user_grade_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grade_name',
        ),
        migrations.AddField(
            model_name='user',
            name='grade_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
