# Generated by Django 3.2.8 on 2022-04-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0065_auto_20220430_1856'),
        ('accounts', '0007_user_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classes_field',
            field=models.ManyToManyField(blank=True, related_name='user', to='course.OnlineClass'),
        ),
    ]
