# Generated by Django 3.2.8 on 2022-04-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_classes_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='classes_field',
        ),
    ]
