# Generated by Django 3.2.8 on 2022-04-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_timefromkonkur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeFromKonkur',
        ),
    ]
